//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasebandProbe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasebandProbe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Categories&gt;
        ///  &lt;Category name=&quot;CategoryVulnerablePlugins&quot;&gt;
        ///    &lt;Name&gt;Yay&lt;/Name&gt;
        ///  &lt;/Category&gt;
        ///  &lt;Category name=&quot;CategorySecurityPolicies&quot;&gt;
        ///    &lt;Name&gt;Yay&lt;/Name&gt;
        ///  &lt;/Category&gt;
        ///  &lt;Category name=&quot;CategoryVulnerableBrowsers&quot;&gt;
        ///    &lt;Name&gt;Yay&lt;/Name&gt;
        ///  &lt;/Category&gt;
        ///&lt;/Categories&gt;.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Modules&gt;
        ///    &lt;Module name=&quot;ModuleWindowsUpdateEnabled&quot;&gt;
        ///        &lt;Name&gt;Windows Updates&lt;/Name&gt;
        ///        &lt;Priority&gt;1&lt;/Priority&gt;
        ///        &lt;Details&gt;
        ///            Having Windows Updates enabled is essential in keeping your system up to date and secure against the latest
        ///            vulnerabilities.
        ///            When a problem is found in Windows that might compromise your security, the vendor creates a patch delivered
        ///            in the form of updates
        ///            to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
    }
}
